title: babakks Blog
email: babak.k.shandiz@gmail.com
description: >-
  This is my professional blog. Here, I'll put things I find interesting or good to know.
baseurl: ""
url: "babakks.github.io"

github_username: babakks

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - favicon.ico

# exclude:
#   - null
