title: Babak K. Shandiz's Blog
email: babak.k.shandiz@gmail.com
description: |
  ✍️ Welcome! This is my professional blog on software development. Here, I'll put things I find interesting or good to know.
github_username: babakks
twitter_username: babakks0
author: babakks
url: "https://babakks.github.io"
baseurl: ""
remote_theme: jekyll/minima
show_excerpts: true
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
include:
  - favicon.ico
data_dir: _data
disqus:
  shortname: babakks
google_analytics: G-W6LPRLMP05
